// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'Button.ce': typeof import('./src/components/CustomElementComps/Button.ce.vue')['default']
    DrawToolType: typeof import('./src/components/DrawRelated/DrawToolType.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    GeojsonValid: typeof import('./src/components/GeojsonValid.vue')['default']
    GeojsonValidDialog: typeof import('./src/components/GeojsonValidDialog.vue')['default']
    GeojsonWktTrans: typeof import('./src/components/GeojsonWktTrans.vue')['default']
    IEpUploadFilled: typeof import('~icons/ep/upload-filled')['default']
    MaptalksMap: typeof import('./src/components/MaptalksMap.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PointPickerContainer: typeof import('./src/components/PointPickerContainer.vue')['default']
    PointTools: typeof import('./src/components/PointTools.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectArea: typeof import('./src/components/SelectArea.vue')['default']
    SpaceDrawContainer: typeof import('./src/components/SpaceDrawContainer.vue')['default']
    SpaceTooltip: typeof import('./src/components/DrawRelated/SpaceTooltip.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
  }
}
