#!/usr/bin/env sh
###
 # @Author: WangNing
 # @Date: 2022-12-27 19:25:37
 # @LastEditors: WangNing
 # @LastEditTime: 2022-12-27 19:28:03
 # @FilePath: /hz-map-tools/.husky/pre-commit
### 
. "$(dirname -- "$0")/_/husky.sh"
 npx --no -- lint-staged
# npm run lint
